---
name: Kocom Wallpad
version: 2025.02.09.001
slug: kocom_py
description: 충북혁신도시센텀클래스
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
url: https://github.com/himg0347/kocom.py
startup: application
boot: auto
uart: true
map:
  - share:rw
options:
  share/kocom/kocom.conf 설정파일: false
  share/kocom/kocom.py 실행파일: false
schema:
  share/kocom/kocom.conf 설정파일: bool
  share/kocom/kocom.py 실행파일: bool
